name:
  base-app-project

services:
  base-app-dev:
    image: base-app-img-dev
    build:
      context: .
      target: dev
    working_dir: /app
    volumes:
      - logs-v:/app/logs
    networks:
      - backend
    ports:
      - "8087:8086"
      - "8001:8000"
    environment: &envs
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-dev/art-registry
      SPRING_DATASOURCE_USERNAME: dmytro
      SPRING_DATASOURCE_PASSWORD: 1111
    depends_on:
      - db-dev

  base-app-prod:
      image: base-app-img-prod
      build:
        context: .
        target: ${TARG-prod}
      working_dir: /app
      volumes:
        - logs-v:/app/logs
      ports:
        - "8086:8086"
        - "8000:8000"
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://192.168.0.103:5432/art-registry
        SPRING_DATASOURCE_USERNAME: dimazhuravlyov
        SPRING_DATASOURCE_PASSWORD: 1111

  db-dev:
    image: postgres:12
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: dmytro
    volumes:
      - database:/var/lib/postgresql/data


networks:
  backend:

volumes:
  logs-v:
  database: