name:
  builder-prod

services:
  base-app:
      image: base-app-img:prod
      build:
        context: .
        target: prod
      volumes:
        - builder_logs_prod_v:/app/logs
      ports:
        - "8080:8080"
      networks:
        - builder_app_net
      environment:
        POSTGRES_URL: ${POSTGRES_URL-jdbc:postgresql://localhost:5432/body_builder_db}
        POSTGRES_USERNAME: ${POSTGRES_USERNAME}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_PASSWORD: ${REDIS_PASSWORD}
      restart: always
      depends_on:
        - redis

  redis:
    image: redis:7.2.3-alpine3.19
    command: '--requirepass ${REDIS_PASSWORD}'
    volumes:
      - builder_redis_v:/data
    ports:
      - "6379:6379"
    networks:
      - builder_app_net

volumes:
  builder_logs_prod_v:
  builder_redis_v:

networks:
  builder_app_net:
