name:
  base-app-project

services:
  base-app-prod:
      image: base-app-img:prod
      build:
        context: .
        target: prod
      working_dir: /app
      volumes:
        - logs_prod_v:/app/logs
      ports:
        - "8086:8086"
      secrets:
        - db_pass
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_IP}:5432/art-registry
        SPRING_DATASOURCE_USERNAME: dimazhuravlyov
      restart: unless-stopped

volumes:
  logs_prod_v:

secrets:
  db_pass:
    environment: "SPRING_DATASOURCE_PASSWORD"
